#!/bin/bash

#
# http://nurkiewicz.blogspot.ru/2012/08/which-java-thread-consumes-my-cpu.html
#
# TL;DR:
# nid in java stacktrace = native thread id (NID)

PID=$(ps -C java -o pid --no-heading --sort -%cpu | head)
# unfortunately ps doesn't seem to sort itself based on thread's CPU
NID=$(ps -L -p $PID -C java -o lwp,c,pid,comm --no-heading --sort -%cpu | sort -k 3 -t ' ' -r | head -n 1 | cut -d ' ' -f 2)
NID=$(printf '%x' $NID)
jstack $PID | grep -A500 $NID | grep -m1 "^$" -B500
